markdown: kramdown
baseurl: /template-portfolio-a
website-title: James Doe
website-description: Portfolio website of James Doe
website-author: James Doe
exclude: ['README.md', '.gitignore']
permalink: pretty
email: chantzis.dimitrios@gmail.com
social:
  - facebook: facebook
    account-id: thejamesdoe
  - provider: instagram
    account-id: thejamesdoe
  - provider: twitter
    account-id: james_doe
include-analytics-tracking: true
google-api-key:
analytics :
  provider : google
  google :
    tracking_id :
collections:
  albums:
    output: true
    permalink: /works/:path/
gems: [
    jekyll-paginate,
    jekyll/tagging,
    jekyll-tagging-related_posts
  ]
disqus:
  comments: false
  url: demodchantzis.disqus.com
paginate: 5
paginate_path: "/news/page:num/"
