markdown: kramdown
baseurl: /template-portfolio-a
url: http://orchid-blossom.cloudvent.net/
website-title: James Doe
website-description: Portfolio website of James Doe
website-author: James Doe
exclude: ['README.md', '.gitignore']
permalink: pretty
email: chantzis.dimitrios@gmail.com
social:
  - provider: facebook
    account-id: thejamesdoe
  - provider: instagram
    account-id: thejamesdoe
  - provider: twitter
    account-id: james_doe
include-analytics-tracking: true
google-api-key:
analytics :
  provider : google
  google :
    tracking_id :
collections:
  albums:
    output: true
    permalink: /works/:path/
gems: [
    jekyll-paginate,
    jekyll/tagging,
    jekyll-tagging-related_posts
  ]
disqus:
  comments: true
  url: demodchantzis.disqus.com
social-share:
  display: true
  media:
    - provider: facebook
      display: true
      sharer-prefix: https://www.facebook.com/sharer/sharer.php?u=
    - provider: twitter
      display: true
      sharer-prefix: https://twitter.com/home?status=
    - provider: reddit
      display: false
      sharer-prefix: //www.reddit.com/submit?url=
    - provider: linkedin
      display: true
      sharer-prefix: https://www.linkedin.com/shareArticle?mini=true&url=
    - provider: pinterest
      display: true
      sharer-prefix: https://pinterest.com/pin/create/button/?url=
    - provider: googleplus
      display: false
      sharer-prefix: https://plus.google.com/share?url=
    - provider: tumblr
      display: true
      sharer-prefix: http://tumblr.com/widgets/share/tool?canonicalUrl=
    - provider: instagram
      display: false
      sharer-prefix:
paginate: 5
paginate_path: "/news/page:num/"
